---
# LoadBalancer IP Pool — VLAN 10 (DMZ: 10.0.10.0/24)
# Für Services die aus dem Internet / der DMZ erreichbar sein sollen.
# IP-Range: 10.0.10.200 - 10.0.10.215 (/28)
#
# Annotation für Services: service.beta.kubernetes.io/cilium-loadbalancer-ip-pool: dmz
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: dmz
spec:
  blocks:
    - cidr: "10.0.10.200/28"
  serviceSelector:
    matchLabels:
      lb-pool: dmz
