---
# macvlan trunk on bond0 â€” VyOS handles VLANs internally via vif sub-interfaces
# Kata's macvtap internetworking creates TAP fd from this macvlan (no TC-filter)
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: trunk-bond0
  namespace: network
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "trunk-bond0",
      "type": "macvlan",
      "master": "bond0",
      "mode": "bridge",
      "mtu": 1500
    }
