---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-60-wifi-sec
  namespace: network
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan-60-wifi-sec",
      "type": "vlan",
      "master": "bond0",
      "vlanId": 60
    }
