---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-200-mgmt
  namespace: network
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan-200-mgmt",
      "type": "vlan",
      "master": "bond0",
      "vlanId": 200,
      "ipam": {}
    }
