---
# WAN: DHCP via VyOS â€” CNI braucht trotzdem eine IP, Link-Local reicht
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-5-wan
  namespace: network
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan-5-wan",
      "type": "vlan",
      "master": "bond0",
      "vlanId": 5,
      "ipam": {
        "type": "static",
        "addresses": [{ "address": "169.254.199.1/32" }]
      }
    }
