---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-50-server
  namespace: network
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan-50-server",
      "type": "vlan",
      "master": "bond0",
      "vlanId": 50,
      "ipam": {
        "type": "static",
        "addresses": [{ "address": "10.0.50.199/24" }]
      }
    }
