---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-40-client
  namespace: network
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan-40-client",
      "type": "vlan",
      "master": "bond0",
      "vlanId": 40,
      "ipam": {}
    }
