---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firewall-credentials
  namespace: network
spec:
  encryptedData:
    vyos-password-hash: AgA9SxE+hyIBbH1Gpuz/CWqAk7aI1JrHMXZHTuJOvyyvLrgg6H5xrXfzyHClwisBifi5LnX1LYqhhhBPUbGcfjChYs1DNlPrqYPsRhdOl1gXRzQ13JVRG+J3xuTKdaDa5S1lPLKUgZPj/vqO512DLD90GkmBMRVjPAdI+0FI4y5cNTdKi1Lg20C9BX5BLAV0K4QPYoqhCS29+XOBlVx1aIHCd0HcmBEAn9Dr4YEchSw2AVqHIi6S0eKaC2GvSnbmwU8DGdu+82UoP4o51y20WOotlz4DNpBhQTC+gFxCJgtQ9HXWH2ss7ZU8ciujXB4gMW5tkg3jggaySnMt6/gnwpScC65egpLefTaoNtquP88ERnejIoRR7bJEcgH+EFm6xe5woDirxuO340jYRoBrkJtC7JUoqDKcxiunrax5Equ5HcM3BiGIMIbI8N5SG55G5MjJbOxio2kB+ikEqzWUfQJ32zhrYX0xB8JJ9NZX2NugLWRq1oqroJasuVVIaCL7QWegCPmiLjBZj82d08xWn65ZQr6x8OY0sSTz2TrbyLyT2hJvghMw7SpujLHvaXT8jxIIPGkHvXNEjDYjpbed+hF3qXAvLrI3T2oEok9cStgl9Fr4euh8aIGan7TW4Q0PgDjF+BWKOn5AcE9C2iZ2KUscpy+fBPUx5r/nzIvkgmwOBc2yjlIuQhm26uGE7Gm0P0jYBJ23Y4kFQ3KTQk9jOQnVqIjW/UclC7nlHU9MKwQ2V+fd8tzyk/iUKaSroO9+KiGtftT1KEuiNVRkc+cYsyIehvhs4uuQzVlLgRDvzwgq6s55rgvEOyXIT/J/fLs42JkXqyEK7A==
  template:
    metadata:
      name: firewall-credentials
      namespace: network
