---
apiVersion: v1
kind: ConfigMap
metadata:
  name: macvtap-deviceplugin-config
  namespace: kube-system
data:
  DP_MACVTAP_CONF: |
    [
      {
        "name"       : "bond0",
        "lowerDevice": "bond0",
        "mode"       : "bridge",
        "capacity"   : 10
      }
    ]
