---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Secrets werden via ksops entschl√ºsselt (ghcr-pull-secret.yaml + cloudinit.yaml)
generators:
  - ksops-generator.yaml

resources:
  - namespace.yaml
  - vm.yaml                 # KubeVirt VM (running: false bis alles ready)
