---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-30-wifi
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan-30-wifi",
      "type": "vlan",
      "master": "bond0",
      "vlanId": 30,
      "ipam": { "type": "dhcp" }
    }
